### ISSUE TITLE
Error after updating to latest version. 'Request' object has no attribute 'is_xhr'

### ISSUE THREAD

**Issue by pochocho** [ucfopen/due-date-changer#24]
Hello After updating to the latest version to get the chrome 80 cookies fix, we started noticing a 500 error when updating assignments. Here's the trace:

```bash
Traceback (most recent call last):
File "/ddchanger/env/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
  response = self.full_dispatch_request()
File "/ddchanger/env/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
  rv = self.handle_user_exception(e)
File "/ddchanger/env/local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
  reraise(exc_type, exc_value, tb)
File "/ddchanger/env/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
File "/ddchanger/env/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
File "/ddchanger/env/src/pylti/pylti/flask.py", line 385, in wrapper
  return function(*args, **kwargs)
File "/ddchanger/lti.py", line 189, in update_assignments
  if not request.is_xhr:
File "/ddchanger/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
  return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
```

To make it work I had to comment [this line](https://github.com/ucfopen/due-date-changer/blob/cfa2276f28fb62b995abf94fe99bd13f6df9907f/lti.py#L189) in lti.py that checks if the request is an ajax request. 

While troubleshooting, I found that this was removed from the werkzeug package in v1.0.0.

**Comment by Thetwam** [comment]
Hey @pochocho, thanks for the issue report! It's embarrassing that we let this one through since our tests actually pick this up, I just apparently didn't run them 😅 

I've got a pull request up (#27) to fix this issue. We also set up Travis to run our tests against every merge to prevent something like this from happening again (#26).

Thanks again!

**Comment by pochocho** [comment]
Thanks @Thetwam
